### ISSUE TITLE
Simple Example of Dependency Injection.

### ISSUE THREAD

**Issue by sirvon** [Prosumma/Guise#2]
Can you show a simple example of injecting some startup dependencies in AppDelegate?

Like registering crash reporting libs, analytics, etc upon startup using Guise.

Thanks!

**Comment by Revolucent** [comment]
@sirvon 

Sure. Unfortunately DI is not a simple topic. Guise can be used for [service location](https://en.wikipedia.org/wiki/Service_locator_pattern) and/or [dependency injection](https://en.wikipedia.org/wiki/Dependency_injection). Some things to note are below. (Note that you may already know some or all of this. I'm writing for anyone who may want to read this.)

### Guise registers types. It does not register libraries or frameworks.

It is not possible to register frameworks in Guise because there is no way to do so in the Swift language. A framework is not something that can be assigned to a variable. It is not a type or an instance. It cannot be returned from a function.

### If you don't reference something elsewhere in your app, it is pointless to register it with Guise.

I tend to use Crashlytics in an initialize-and-forget manner. I initialize it in my `AppDelegate` and then forget about it, letting it do its job. Because I never reference it elsewhere in the application, there is no point in registering it with Guise.

### Guise registers factories which create types upon which other types depend for their initialization.

I think the best way to show an example of this is to write an Example app. I'm doing that at the moment.

**Comment by sirvon** [comment]
the service locator usage is the one I'm aiming for...

UserService.swift
EventService.swift
AnalyticService.swift

Using those services in my ViewModels and using Realm and other Types in those services.

Thank you for the explanations, would definitely like to learn more from your forthcoming Example app.

**Comment by invoy-ghigley** [comment]
@sirvon I'm working on it. Sorry for the slow response but I have a dayjob and I had the bad luck to get sick.

**Comment by Revolucent** [comment]
OK, @sirvon, it's going to be some time—perhaps as much as a month or more—before I can get something out the door. In the meantime, here's something _very_ quick that I'm just going to put inline here.

I have not tried to compile this code. It should be regarded as pseudocode. And it is also incomplete, because the definitions of some of the classes are not given, but assumed.

```swift

import Guise
import XCLogger

struct Api {
  let logger: XCGLogger?

  init(logger: XCGLogger? = nil) {
    self.logger = logger
  }
}

protocol UsesApi {
  var api: Api! { get set }
}

protocol Logged {
  var logger: XCGLogger? { get set }
}

class AppDelegate {

  override init() {
    super.init()     
    // Register dependencies as early as possible.
    registerDependencies()
    registerKeyPathInjections()
  }

  func registerDependencies() {
    let logger = XCGLogger.default
    logger.setup(/* etc. */)
    Guise.register(instance: logger) 
    /*
    Here is an example of Init Injection.
    When we ask Guise for an instance of our Api,
    it will automatically pass it whatever logger
    instance is registered. Or nil if one is not.
    */
    Guise.register(instance: Api(logger: Guise.resolve()))
  }

  func registerKeyPathInjections() {
    Guise.into(injectable: UsesApi.self).inject(\.api).register()
    Guise.into(injectable: Logged.self).inject(\.logger).register()
  }
}                                  

class AwesomeViewController: UIViewController, UsesApi, Logged {
  var api: Api!
  var logger: XCGLogger?

  override func viewDidLoad() {
    super.viewDidLoad()
    // Because AwesomeViewController implements UsesApi and Logged,
    // The next line of code "hydrates" the logger and api ivars,
    // because these were set up in registerKeyPathInjections()
    // in the AppDelegate.
    Guise.resolve(into: self)
  }
}
```

This uses the as-yet unreleased `v7.0` of Guise, which you can find in the [`v7.0` branch](https://github.com/Prosumma/Guise/tree/v7.0). This version supports `KeyPath` injection, which you can use with classes (such as view controllers) which you do not generally instantiate directly.

**Comment by Revolucent** [comment]
The `v7.0` branch is mostly stable, but may change a little bit before release. The API and implementation of KeyPath injection may undergo some minor changes, and then it all needs to be documented before I can release it. A lot of work.

**Comment by Revolucent** [comment]
By the way, if you don't want to use KeyPath injection, here's an alternate implementation of `AwesomeViewController`.

```swift
class AwesomeViewController: UIViewController {
  var api: Api!
  var logger: XCGLogger?

  override func viewDidLoad() {
    super.viewDidLoad()
    logger = Guise.resolve()
    api = Guise.resolve()
  }
}
```

**Comment by Revolucent** [comment]
OK, @sirvon. If you look in the `v7.0` branch, you'll see a very simple example project. It's so simple I call it Skeleton. However, one big advantage of it is that you can step through the code to see what is happening. It references the Guise project directly, so you can even set breakpoints inside of Guise to understand what it is doing.

**Comment by sirvon** [comment]
Thank you for these examples and commentary. I will review and implement this week.
